
[2025-05-21 00:32:03.537490] Error: 
Traceback (most recent call last):
  File "C:\Users\alfon\PycharmProjects\PythonProject\main.py", line 96, in <module>
    main()
  File "C:\Users\alfon\PycharmProjects\PythonProject\main.py", line 78, in main
    root.iconphoto(True, tb.PhotoImage(
                         ^^^^^^^^^^^^^^
  File "C:\Users\alfon\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 4140, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\alfon\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 4087, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError

[2025-05-21 00:32:26.902900] Error: 
Traceback (most recent call last):
  File "C:\Users\alfon\PycharmProjects\PythonProject\main.py", line 96, in <module>
    main()
  File "C:\Users\alfon\PycharmProjects\PythonProject\main.py", line 78, in main
    root.iconphoto(True, tb.PhotoImage(
                         ^^^^^^^^^^^^^^
  File "C:\Users\alfon\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 4140, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\alfon\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 4087, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError

[2025-05-21 00:35:11.705623] Error: 
Traceback (most recent call last):
  File "C:\Users\alfon\PycharmProjects\PythonProject\main.py", line 96, in <module>
    main()
  File "C:\Users\alfon\PycharmProjects\PythonProject\main.py", line 78, in main
    root.iconphoto(True, tb.PhotoImage(
                         ^^^^^^^^^^^^^^
  File "C:\Users\alfon\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 4140, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\alfon\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 4087, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError
